"""add chat_daily_summaries and important_people

Revision ID: 9717c4b8dee6
Revises: a7af7459d5b1
Create Date: 2026-04-02 11:47:26.923489
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9717c4b8dee6'
down_revision: Union[str, None] = 'a7af7459d5b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_daily_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_name', sa.String(length=255), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_name', 'summary_date', name='uq_chat_daily_summary')
    )
    op.create_index('idx_chat_summary_date', 'chat_daily_summaries', ['summary_date'], unique=False)
    op.add_column('user_settings', sa.Column('important_people', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'important_people')
    op.drop_index('idx_chat_summary_date', table_name='chat_daily_summaries')
    op.drop_table('chat_daily_summaries')
    # ### end Alembic commands ###
