"""initial schema

Revision ID: a7af7459d5b1
Revises: 
Create Date: 2026-04-01 15:37:26.293838
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7af7459d5b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('source_chat', sa.String(length=255), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('reply_to_text', sa.Text(), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('extracted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extracted_people', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('extracted_topic', sa.String(length=512), nullable=True),
    sa.Column('ai_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_index('idx_messages_created_at', 'messages', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_messages_source_created', 'messages', ['source', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_messages_status', 'messages', ['status'], unique=False)
    op.create_index('idx_messages_status_created', 'messages', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('monitored_chats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ignored_chats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quiet_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('digest_time', sa.String(length=5), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_user_id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_active', 'tasks', ['is_done', 'due_date'], unique=False, postgresql_where=sa.text('NOT is_done'))
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reminders_pending', 'reminders', ['remind_at'], unique=False, postgresql_where=sa.text('NOT sent'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reminders_pending', table_name='reminders', postgresql_where=sa.text('NOT sent'))
    op.drop_table('reminders')
    op.drop_index('idx_tasks_active', table_name='tasks', postgresql_where=sa.text('NOT is_done'))
    op.drop_table('tasks')
    op.drop_table('user_settings')
    op.drop_index('idx_messages_status_created', table_name='messages')
    op.drop_index('idx_messages_status', table_name='messages')
    op.drop_index('idx_messages_source_created', table_name='messages')
    op.drop_index('idx_messages_created_at', table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
